# Generated by Django 3.1.12 on 2021-06-26 11:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Post', models.TextField()),
                ('post_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='Draft', max_length=10)),
                ('post_created', models.DateTimeField(verbose_name=datetime.datetime(2021, 6, 26, 11, 13, 48, 947452, tzinfo=utc))),
                ('post_published', models.DateTimeField(auto_now_add=True)),
                ('post_updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
