# Generated by Django 3.1.12 on 2021-06-26 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210626_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
